### PR TITLE
PAM Token Management System

### PR DESCRIPTION
**Pull request by CraigLn**

### CODE REVIEW

**Comment by madisonsmith** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- Sources/PubNub/Helpers/CBOR/CBORDecoder.swift  55
- Sources/PubNub/Helpers/CBOR/CBORSerialization.swift  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/PubNub/swift/pullRequest?prid=4802273&bid=15980844)

**Comment by CraigLn** [comment]
This also includes a fix for [CE-4270](https://pubnub.atlassian.net/browse/CE-4270): HereNow 404 due to missing comma when only groups are provided.

**Comment by raipubnub** [comment]
Looks good from here but I don't see the tokens getting added to the objects endpoints. Is that in a separate PR?

**Comment by CraigLn** [comment]
@raipubnub Yeah this story was just for TMS, so no objects integration was done as part of this.

**Pull request merged**
